// GENERATED by tools/seed-gauntlet.mjs — do not edit by hand. Re-run: npm run seed:gauntlet.
// Import-only (leading underscore keeps Pages from routing it as an endpoint).
export const HEADER_HEX = "474554202e2f636865636b2d696e2e6a736f6e20e28094206d696e642074686520616c672e2073686172642d313a656d62657277697265";
export const GATE_PATHS = {
  "/root/check-in.json": "g1",
  "/root/.well-known/cce101c1df795748.json": "g2",
  "/root/a/878cbc787ed74c1d.png": "g3",
  "/root/a/33309ad8ea9b79e6.txt": "g4seal",
  "/root/a/fe211d87b44170d2.txt": "g4open"
};
